---
author: "Laurine Seelt"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
---

# Package

Packages can be very useful when working in R. Here, I demonstrate how I've created the package called .. <br>
This package can be used to ..
<br>
```{r setting up, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```


```{r, eval=FALSE}
df_summary <- df %>% summarise(mean = mean(x), sd = sd(x))
df %>% filter() %>%
  ggplot(aes(x = x, y = y, colour = z))+
  geom_point()+
  theme_classic()+
  labs(title = "",
       x = "",
       y = "")
```


```{r example, eval=FALSE}
hematocrit_paired <- read_csv2(here::here("Data/hematocrit_paired"))

hematocrit_tidy <-  pivot_longer(data = hematocrit_paired, cols = c(voor, na),  
                                 names_to = "condition",  values_to = "hematocrit")
hematocrit_tidy_summary <- hematocrit_tidy %>% group_by(condition) %>%
  summarize(mean = mean(hematocrit), stdev = sd(hematocrit))

shapiro.test(voor en na) %>% leveneTest() %>% t.test()
hematocrit_tidy %>% leveneTest()

hematocrit_tidy_summary %>% ggplot(aes(x = condition, y = mean, fill = condition))+
  geom_bar(stat = "identity")+
  geom_errorbar(aes(ymin = mean - stdev, ymax = mean + stdev), width = 0.2)+
  theme_minimal()+
  labs(title = "Hematocrit values before and after an altitude workout",
       subtitle = "errorbars depict 1 standard devation",
       x = "Condition",
       y = "Hematocrit (%)")+
  theme(legend.position = "none", text = element_text(size=14))
```
